@startuml
!theme plain
skinparam defaultTextAlignment center
skinparam defaultFontName Consolas
skinparam classAttributeIconSize 0
hide circle

folder "/" as root
folder "home" as home
folder "ei00" as ei00
folder "ei00000" as ei00000
folder "prog" as prog
folder "kongestu" as kongestu
rectangle "main.c" as main_c

' 構造をつなぐ
root -down-> home
home -down-> ei00
ei00 -down-> ei00000
ei00000 -down-> prog
ei00000 -down-> kongestu
prog -down-> main_c

' 現在地を示す注釈
note left of ei00
  今、ここに  
  いるとする
end note

' パスの説明（右側の注釈）
note right of root
  ../..  
  「一つ上」の「一つ上」
end note

note right of home
  ..  
  「一つ上」
end note

note right of ei00
  .  
  「現在いるところ」
end note

note right of ei00000
  ei00000  
  （./ei00000 でもいい。以下も同様）
end note

note right of kongestu
  ei00000/kongestu  
  「ei00000」の中の「kongestu」
end note

note right of prog
  ei00000/prog  
  「ei00000」の中の「prog」
end note

note right of main_c
  ei00000/prog/main.c  
  「ei00000」の中の「prog」の中の「main.c」
end note

@enduml
